### ISSUE TITLE
This project is outdated and hasn't been maintained

### ISSUE THREAD

**Issue by shaynevanasperen** [netfx/extensions#2]
I like the idea of this project. I liked it so much that I decided to create an alternative, more modern and up-to-date version of this project. I called it "[Quarks](https://github.com/shaynevanasperen/Quarks)". Here's a brief description:

A collection of source-only [NuGet packages](https://www.nuget.org/packages?q=quarks) representing tiny bits of functionality that don't belong together in a monolithic "utility" library. These are typically delivered as self-contained source files added to your projects as internal classes that can be easily kept up-to-date with NuGet.

The name "Quarks" was chosen for these packages' root namespace to signify that they are very small, fundamental building blocks in your application, just like in quantum physics:

    A quark is an elementary particle and a fundamental constituent of matter.

The inspiration for creating this collection of packages was born out of my own frustrations related to bundling miscellaneous helpers into a monolithic library, seeing it done before in NETFx, and from reading a blog post titled [Packaging Source Code With NuGet](http://nikcodes.com/2013/10/23/packaging-source-code-with-nuget). I decided to create this project instead of contribute to NETFx because I was frustrated with how cumbersome it is to contribute new packages to NETFx, as well as the fact that NETFx packages are not marked as [development dependencies](https://docs.nuget.org/release-notes/nuget-2.8#development-dependencies).

See the project's GitHub page here: [https://github.com/shaynevanasperen/Quarks](https://github.com/shaynevanasperen/Quarks)

**Comment by kzu** [comment]
[Bad timing](http://blog.nuget.org/20150729/Introducing-nuget-uwp.html) to start that and good luck shipping anything with /content in it ;)

This approach is basically dead because of NuGet 3.1.
